/* Curated October 8, 2026. Official venue pages linked per record. Images are served by venue websites and remain credited to their owners. */
window.VENUES = [
{
 id:"wilsons",name:"Wilson’s Coastal Club",town:"Boutiliers Point",region:"HRM & St. Margaret’s Bay",lat:44.6681912,lng:-63.9622205,
 archetype:"Private beach & cottages",style:"Relaxed coastal",rank:6,score:"Spectacular private beach, but the required buyout adds complexity.",
 capacity:107,capacityNote:"Up to 65 non-overnight guests plus at most 42 staying on site. 100 guests needs substantial cottage occupancy; do not assume 107 freely interchangeable places.",
 stay:"Up to 42 overnight guests across nine cottages per wedding policy.",beds:42,stayRule:"All nine cottages must be reserved for 3 nights in September 2027, plus a separate wedding surcharge.",stayFlag:"Required multi-night buyout",
 base:null,baseLabel:"Wedding surcharge and full cottage rental: quote required",priceType:"unknown",minFoodBar:0,
 location:"7532 St. Margaret’s Bay Road, Boutiliers Point, NS",map:"https://maps.app.goo.gl/1o9g7MudQtCHqbiv7",
 site:"https://wilsonscoastalclub.com/weddings",sources:[["Wedding terms","https://wilsonscoastalclub.com/weddings"],["Published 2027 cottage rates","https://wilsonscoastalclub.com/cottages"]],
 email:"info@wilsonscoastalclub.com",phone:"902-425-4662",
 hero:"assets/wilsons-hero.jpg",
 images:[
 ["assets/gallery/wilsons-1.jpg","Private beachfront setting"],
 ["assets/gallery/wilsons-2.jpg","Coastal wedding grounds"],
 ["assets/gallery/wilsons-3.jpg","Beachfront wedding location"]
 ],
 overview:"A collection of private seaside cottages with exclusive beach and breakwater access. Beautiful for a relaxed oceanside weekend, but you would create the reception setup with outside vendors rather than simply walk into a ballroom.",
 ceremony:"Beachfront or breakwater ceremony. Tides should be considered for scheduling.",
 reception:"Outdoor event with your own vendors, décor and potentially a rented tent. Indoor seated rain backup not confirmed.",
 included:["Exclusive access to private waterfront when cottages are booked","Use of existing resort grounds and amenities","Outside wedding vendors permitted"],
 extra:["Three-night accommodation buyout for all nine cottages in September","Separate wedding surcharge","Catering, bar, tent, seating, service, rentals and cleanup as required"],
 risks:["2027 September is Beach Season; three-night minimum","Capacity splits overnight and day guests","A proper tent and rain contingency may add substantially to cost"],
 questions:["What is the all-in September 2027 three-night cottage buyout plus wedding surcharge?","Can individual guests pay for their cottages, and who guarantees unbooked units?","Can 100 guests attend if only 25 stay overnight?","Can a tent, live music and dancing run until midnight?","What is the approved indoor rain plan and who handles setup/cleanup?"],
 imageCredit:"Wilson’s Coastal Club website; wedding imagery credited there to Katharina Mayer / Earth and Honey Photography Co."
},
{
 id:"farm",name:"The Farm at South Cove",town:"Lunenburg",region:"South Shore",lat:44.365344,lng:-64.339698,
 archetype:"Design-led coastal barn",style:"Elegant barn",rank:1,score:"White barn, waterfront grounds, unusually flexible supplier model. Wedding pricing and hours need clarification.",
 capacity:150,capacityNote:"Barn seats up to 150. Confirm dinner plus dancing layout for 100-125.",
 stay:"Farmhouse sleeps 10; three waterfront lofts and glamping bunkies also offered. Total bed count and booking requirements not confirmed.",beds:null,stayRule:"Accommodations separate; wedding-specific stay requirements not confirmed.",stayFlag:"Some on-site stays",
 base:4500,baseLabel:"$4,500 + HST advertised for venue-space package. NOT confirmed as a Saturday wedding rate.",priceType:"venue-space",minFoodBar:0,
 location:"768 Mason’s Beach Road, Lunenburg, NS",map:"https://maps.app.goo.gl/ZPvYjyvWMkgfQmkaA",
 site:"https://www.farmatsouthcove.ca/the-venue-package",sources:[["Venue-space inclusions and $4,500 rate","https://www.farmatsouthcove.ca/the-venue-package"],["Wedding-specific inquiry","https://www.farmatsouthcove.ca/contact"],["Farmhouse accommodation","https://www.farmatsouthcove.ca/farmhouse"],["Waterfront lofts","https://www.farmatsouthcove.ca/lofts-2"]],
 email:"sally@farmatsouthcove.ca",phone:"902-298-0488",
 hero:"assets/farm-hero.jpg",
 images:[
 ["assets/gallery/farm-1.jpg","South Cove property aerial"],
 ["assets/gallery/farm-2.jpg","Barn space"],
 ["assets/gallery/farm-3.jpg","Venue interior"]
 ],
 overview:"A very polished whitewashed barn on coastal Lunenburg grounds with a pond, fire pit, farmhouse, modern loft suites and bunkies. The design can look refined rather than traditionally rustic.",
 ceremony:"Outdoor grounds and waterfront available; exact ceremony fee and fallback not published.",
 reception:"White barn with harvest tables, chairs, full dinnerware and sound system. Advertised access is 2 PM–10 PM for the venue-space package.",
 included:["Harvest tables and chairs for 150","Dinnerware and cutlery for 150","Prep kitchen with fridges and ovens","Bar prep space with sinks and ice freezer","Sound system, microphone and mixer","On-site staff and venue coordinator","BYO alcohol and choose your own bartenders (licence required)"],
 extra:["Caterer, waitstaff, bartenders, alcohol, licences","Wedding-specific pricing or fees may differ from advertised event-space package","Accommodation, photographer, DJ, linens and additional décor","Verify teardown/dishwashing responsibility"],
 risks:["The $4,500 advertised rate is not explicitly a full wedding-package quote","Website advertises 2 PM–10 PM venue-space access; later wedding finish times must be approved in writing","Cleanup, dishwashing and outside vendor scope require a contract"],
 questions:["What is the actual September 2027 Saturday wedding package and what fees differ from the $4,500 venue-space package?","Can DJ and dancing run until midnight or 1 AM? Can the fire pit continue afterwards?","When can vendors load in and when must everyone leave?","Who handles dishes, garbage, teardown and cleaning?","Are any accommodations mandatory and can guests book them individually?","Does the ceremony or backup have a separate fee?"],
 imageCredit:"Farm at South Cove official gallery. Photography rights remain with original photographers."
},
{
 id:"quarterdeck",name:"Quarterdeck Resort",town:"Summerville Centre",region:"South Shore",lat:43.9541862,lng:-64.8131407,
 archetype:"Contemporary beach resort",style:"Modern coastal",rank:3,score:"Bright modern reception venue by a superb beach; ideal if the guest count settles at 100 or fewer.",
 capacity:100,capacityNote:"Champlain Centre published capacity is 100; confirm whether that includes dinner with dance floor.",
 stay:"Oceanfront villas, suites and a guest house that sleeps up to 10. Total room count and wedding room block not confirmed.",beds:null,stayRule:"On-site rooms available; wedding room minimums not published.",stayFlag:"Guest rooms available",
 base:null,baseLabel:"2027 wedding package: quote required",priceType:"unknown",minFoodBar:0,
 location:"5 Willow Lane, Summerville Centre, NS",map:"https://maps.app.goo.gl/u7t5CMWvX4ZfjrLb9",
 site:"https://www.quarterdeck.ca/event-inquiry/wedding-events/",sources:[["Weddings","https://www.quarterdeck.ca/event-inquiry/wedding-events/"],["Event-room capacities","https://www.quarterdeck.ca/event-inquiry/event-venues/"],["Resort accommodation and guest house","https://www.quarterdeck.ca/quarterdeck-story/"]],
 email:"events@quarterdeck.ca",phone:"902-683-2998",
 hero:"assets/quarterdeck-hero.jpg",
 images:[
 ["assets/gallery/quarterdeck-1.jpg","Wedding by the coast"],
 ["assets/gallery/quarterdeck-2.jpg","Wedding reception atmosphere"],
 ["assets/gallery/quarterdeck-3.jpg","Wedding at Quarterdeck"]
 ],
 overview:"A contemporary resort overlooking Summerville Beach, with a dedicated event centre, indoor dining, in-house culinary services and modern coastal accommodations. One of the least rustic options on the list.",
 ceremony:"Beachside ceremony setting; weather contingency to be confirmed.",
 reception:"Champlain Centre seats up to 100 under the venue's published capacity listing. Built-in sound and microphone, tables and chairs.",
 included:["Event team and on-site staff","Tables, chairs, plates, flatware and glassware","Access to in-house culinary team and customizable menus","Audio system and wireless microphone"],
 extra:["Reception room and ceremony fees not published","Menu and bar spend not published","On-site lodging booked separately unless contract specifies otherwise"],
 risks:["100 is the published maximum for Champlain Centre","Need confirm 100 seated guests PLUS a dance floor","Not all event rooms overlook the beach; Ocean Room is a different 48-person room"],
 questions:["Does the Champlain Centre seat 100 for dinner with a dance floor, or fewer?","Can the ceremony happen on the beach and what is the rain plan?","2027 venue fee, per-person catering, bar and minimum spend?","Do you require a room block or minimum rooms?","Do the reception-room windows have direct ocean views?","What time does the music need to end?"],
 imageCredit:"Quarterdeck Resort official wedding gallery."
},
{
 id:"bull",name:"Bull Point Estate",town:"Port Mouton",region:"South Shore",lat:43.8886538,lng:-64.7911096,
 archetype:"Private oceanfront estate",style:"Elegant estate",rank:2,score:"Possibly the best aesthetic match: dramatic Atlantic setting, purpose-built elegant venue, and overnight estate accommodation.",
 capacity:200,capacityNote:"Official event venue advertises capacity for 200; verify seated dining configuration.",
 stay:"Ocean House sleeps about 12 and Cottage sleeps 6; approximately 18 on-site. Confirm actual 2027 rental inventory.",beds:18,stayRule:"Wedding accommodation requirements and package pricing must be requested.",stayFlag:"Estate accommodation",
 base:null,baseLabel:"Wedding pricing brochure by inquiry; no public figure verified",priceType:"unknown",minFoodBar:0,
 location:"1203 Central Port Mouton Road, Port Mouton, NS",map:"https://maps.app.goo.gl/rNHecuKb8CnjMBXa9",
 site:"https://www.bullpoint.ca/weddings",sources:[["Venue and inclusions","https://www.bullpoint.ca/venue"],["Wedding packages","https://www.bullpoint.ca/weddings"],["Contact","https://www.bullpoint.ca/contact-us"]],
 email:"sally@farmatsouthcove.ca",phone:"902-298-0488",
 hero:"assets/bull-hero.jpg",
 images:[
 ["assets/gallery/bull-1.jpg","Bull Point property"],
 ["assets/gallery/bull-2.jpg","Estate reception venue"],
 ["assets/gallery/bull-3.jpg","Wedding event"]
 ],
 overview:"A 50-acre private estate with roughly 1,500 feet of shoreline, two accommodation buildings, and a purpose-built venue that feels more architectural than barn-like.",
 ceremony:"Waterfront estate setting; exact ceremony location, inclusions and weather backup require quote.",
 reception:"White harvest tables, white cross-back chairs, polished concrete, expansive patio and commercial catering kitchen.",
 included:["25 white harvest tables and 200 white cross-back chairs","Industrial catering kitchen","Separate bar area","Seven washrooms, including accessible facilities","Accessible event-space main floor","Patio overlooking the coast"],
 extra:["Wedding fee and accommodation rentals are not published","Catering, bar staffing and external services depend on selected wedding package","Transportation for guests travelling from Halifax"],
 risks:["Pricing brochure is inquiry-only","Travel time and nearby off-site accommodation need planning","Party end time and weather alternative not confirmed"],
 questions:["Can you share the September 2027 wedding brochure and available Saturdays?","Is there a mandatory Ocean House and Cottage rental? If so, what is the minimum stay?","What is included in the wedding package versus venue-only hire?","Can 100 guests dance inside comfortably and until what time?","Who is responsible for catering, bar licences, linens and cleanup?"],
 imageCredit:"Bull Point Estate official photography gallery, with original photographers credited by venue."
},
{
 id:"pomquet",name:"Pomquet Beach Cottages",town:"Pomquet",region:"Northumberland Shore",lat:45.6427192,lng:-61.8252792,
 archetype:"Harbour-view event centre",style:"Modern practical",rank:5,score:"Exceptional published rental value and indoor backup. Less exclusive-estate aesthetic; farther from Halifax.",
 capacity:150,capacityNote:"Harbourview Event Centre advertises 150-person capacity with indoor bad-weather option.",
 stay:"Five cottages (four 2-bedroom, one accessible 1-bedroom) plus a 1-bedroom loft advertised. Starting cottage rates from $219/night; maximum sleeping headcount and September minimum stay require confirmation.",beds:null,stayRule:"Accommodation is an optional enquiry field; no compulsory buyout identified.",stayFlag:"Cottages available",
 base:1200,baseLabel:"$1,200 CAD/day published event-centre rental; confirm 2027 wedding dates",priceType:"published",minFoodBar:0,
 location:"198 Pomquet Beach Road, Pomquet, NS B2G 2L4",map:"https://maps.app.goo.gl/FyTaX89vgvZtTMJC7",
 site:"https://pomquetbeachcottages.com/harbourview-event-centre/",sources:[["Harbourview Event Centre and pricing","https://pomquetbeachcottages.com/harbourview-event-centre/"],["Cottage rates","https://pomquetbeachcottages.com/"]],
 email:"contactus@pomquetbeachcottages.com",phone:"902-971-0314",
 hero:"assets/pomquet-hero.jpg",
 images:[
 ["assets/gallery/pomquet-1.jpg","Harbourview Event Centre"],
 ["assets/gallery/pomquet-2.jpg","Event room"],
 ["assets/gallery/pomquet-3.jpg","Venue grounds"]
 ],
 overview:"An affordable purpose-built harbour-view hall on scenic grounds close to cottages. Less luxury boutique, but far simpler logistics and one of the clearest published rates.",
 ceremony:"Waterfront grounds and indoor rain option are advertised.",
 reception:"2,560-square-foot accessible, climate-controlled centre with outdoor seating; 12 noon to 12 noon daily access.",
 included:["Seating, tables and dinnerware for 150","Kitchen, sound system and bar area","Indoor bad-weather option","Heated and air-conditioned accessible event hall","Full-day rental from noon to noon"],
 extra:["Bartenders, alcohol and liquor permits","Catering and any additional decorative rentals","Cleanup, garbage sorting and removal","On-site cottage stays priced separately"],
 risks:["Cleaning is expressly excluded from rental","Less luxe than private estate alternatives","Longer travel from HRM"],
 questions:["Is $1,200/day valid for September 2027 weddings? Any ceremony or cleaning fees?","Can we see seated layouts for 100 and 125 with a dance floor?","Is there a music cutoff or sound limit?","How many guests can sleep on-site and what are September rates?","Can we use any caterer and bar service?"],
 imageCredit:"Pomquet Beach Cottages official venue galleries."
},
{
 id:"anchorage",name:"Anchorage House & Cottages",town:"Hubbards",region:"HRM & St. Margaret’s Bay",lat:44.6400786,lng:-64.0540681,
 archetype:"Victorian waterfront house & tent",style:"Classic coastal",rank:4,score:"Very good mid-size wedding package: cove views, lots of cottages, and unusually broad inclusions.",
 capacity:80,capacityNote:"Official Classic Wedding Package is for up to 80 guests.",
 stay:"Eleven cottages plus a sleeping cabin advertised; 40+ people can stay on site. The historic house offers additional lodging arrangements.",beds:40,stayRule:"Group cottage bookings offered as add-ons; confirm minimum length in September (peak season through Sep 15).",stayFlag:"40+ overnight places",
 base:8500,baseLabel:"$8,500 CAD + HST advertised Classic Wedding Package (up to 80)",priceType:"published",minFoodBar:0,
 location:"56 Shore Club Road, Hubbards, NS",map:"https://maps.app.goo.gl/G8iMKToc5ZMi6DZp7",
 site:"https://www.anchoragehouse.com/nova-scotia-inn-cottages/weddings-events/weddings/",sources:[["Detailed wedding package","https://www.anchoragehouse.com/nova-scotia-inn-cottages/weddings-events/weddings/"],["Accommodation policies","https://anchoragehouse.com/nova-scotia-inn-cottages/accommodations/rates/"]],
 email:"",phone:"902-857-9402",
 hero:"assets/anchorage-hero.jpg",
 images:[
 ["assets/gallery/anchorage-1.jpg","Wedding at Anchorage House"],
 ["assets/gallery/anchorage-2.jpg","Outdoor celebration"],
 ["assets/gallery/anchorage-3.jpg","Garden wedding"]
 ],
 overview:"A Victorian waterfront house and cottage collection overlooking Hubbards Cove. The standard package includes a reception tent, full tableware, dance floor and event support, which reduces surprise rental expenses.",
 ceremony:"Front lawn by the water, with a wedding arch and 80 ceremony chairs included.",
 reception:"1,200-square-foot wedding tent with dance floor and lighting on the property's lawn.",
 included:["1,200 sq ft reception tent with setup and teardown","80 ceremony chairs, 8 reception rounds, head and ancillary tables","Tableware, glassware, table linens and napkins","Dance floor, lighting, power and wedding arch","Special Occasion Licence according to website","Full day-of coordination, decorating, setup and cleanup","Use of pool, dock, kayaks and fire pits"],
 extra:["Catering and bar purchase/service","Accommodation or full weekend extension","Photography, music and flowers"],
 risks:["Package is limited to 80 guests, not 100","The reception is in a tent, not an indoor ballroom","September 1–15 overlaps property peak-season accommodation rules"],
 questions:["Is the $8,500 package available on September 2027 Saturdays?","How does the tent handle wind, heavy rain and cool evenings?","Is there a lodging minimum or is booking cottages optional?","What are alcohol service arrangements under the included Special Occasion Licence?","How late can music continue?"],
 imageCredit:"Anchorage House & Cottages wedding photography from official site."
},
{
 id:"oceanbay",name:"Ocean Bay View Luxury Guesthouse",town:"Musquodoboit Harbour",region:"Eastern Shore",lat:44.7785527,lng:-63.1512672,
 archetype:"Private luxury seaside house",style:"Private villa",rank:7,score:"Closest to a private coastal château for 50 people, but contractually too small for a 75-125-person wedding.",
 capacity:50,capacityNote:"Published contract states a 50-person maximum. Additional attendance requires advance written permission and fees; do not assume 100 can attend.",
 stay:"Five ensuite guest suites sleeping up to 10.",beds:10,stayRule:"Two-night whole-house booking INCLUDED in the $6,000 starting package; $2,000 refundable deposit additional.",stayFlag:"Two-night stay included",
 base:6000,baseLabel:"$6,000 starting package including tax and a two-night whole-house stay; $2,000 refundable security deposit extra",priceType:"tax-included",minFoodBar:0,
 location:"78 Clamshell Road, Musquodoboit Harbour, NS",map:"https://maps.app.goo.gl/nMcCkcJLdCsD92fe6",
 site:"https://www.oceanbayview.ca/weddings",sources:[["Wedding pricing","https://www.oceanbayview.ca/weddings"],["Official event contract / 50-person limit","https://www.oceanbayview.ca/_files/ugd/b1edcc_8ff265b8881249b494b9cb14162b12b2.pdf"]],
 email:"service@oceanbayview.online",phone:"902-440-5848",
 hero:"assets/oceanbay-hero.jpg",
 images:[
 ["assets/oceanbay-hero.jpg","Oceanfront guesthouse and grounds"],
 ["assets/gallery/oceanbay-1.jpg","Glass sunroom and bright interiors"],
 ["assets/gallery/oceanbay-2.jpg","Water-view hot tub and outdoor grounds"]
 ],
 overview:"A luxury oceanfront guesthouse with manicured gardens, dock, five ensuite guest rooms and spa-like amenities. Strongest intimate private-house aesthetic, but not suitable for a normal 100-person wedding under the advertised contract.",
 ceremony:"Private garden and waterfront dock locations.",
 reception:"Garden or house-based intimate celebrations; formal tent and large indoor backup not established.",
 included:["Two-night whole-house rental for five suites","Event-use fee and cleaning fee","Hot tub, dry sauna, steam room, kitchen and games room","Continental breakfast for house guests"],
 extra:["External catering, music, bar, rentals and coordination","Refundable $2,000 security deposit","Written approval needed to exceed 50 total guests"],
 risks:["Firm 50-person event-contract maximum without written exception","Package includes tax but not external wedding services","50 guests may still require rain tent"],
 questions:["Is there any approved possibility of 75 guests, and if so what written occupancy limit?","What tents or indoor rain backups are allowed?","Do the $6,000 starting rates apply in September 2027?","Can music continue past 10 PM and are there noise restrictions?"],
 imageCredit:"Ocean Bay View official wedding website image."
},
{
 id:"oceanstone",name:"Oceanstone Resort & Spa",town:"Indian Harbour",region:"HRM & St. Margaret’s Bay",lat:44.5207672,lng:-63.9365005,
 archetype:"Boutique coastal resort & spa",style:"Coastal resort",rank:8,score:"Beautiful shoreline and full-service experience; historical minimum and accommodation commitments are substantial.",
 capacity:80,capacityNote:"80 is a third-party published event capacity. Older materials mention more and tent options; resort must confirm 2027 seated maximum, especially for 100.",
 stay:"21 total accommodation units referenced in the official 2027 guide; exact sleeping capacity and rates to request.",beds:null,stayRule:"2025 weekend package required a two-night booking of all waterfront cottages, suites and lodge rooms. 2027 guide says exclusive use applies when all 21 units are reserved; current mandatory minimum not confirmed.",stayFlag:"Possible resort buyout",
 base:10000,baseLabel:"Historical 2025 in-season weekend: $10,000 facility fee + $14,000 minimum food & beverage, BEFORE required lodging. 2027 quote unavailable.",priceType:"historical",minFoodBar:14000,
 location:"8650 Peggy’s Cove Road, Indian Harbour, NS",map:"https://maps.app.goo.gl/QZwTBs4Hg34UHbkS6",
 site:"https://oceanstoneresort.com/weddings/",sources:[["2027 Wedding Guide","https://oceanstoneresort.com/wp-content/uploads/2026/07/Oceanstone-Wedding-Venue-Guide-2027-Website.pdf"],["Historical 2025 wedding price sheet","https://oceanstoneresort.com/wp-content/uploads/2024/04/2025-Signature-Wedding-Packages.pdf"],["Wedding overview","https://oceanstoneresort.com/weddings/"]],
 email:"weddings@oceanstoneresort.com",phone:"902-821-3047",
 hero:"assets/oceanstone-hero.jpg",
 images:[
 ["assets/oceanstone-ceremony.jpg","Oceanfront ceremony area"],
 ["assets/oceanstone-table.jpg","Wedding dining at Oceanstone"],
 ["assets/oceanstone-shore.jpg","Couple on the shoreline"]
 ],
 overview:"A boutique resort with rocky Atlantic ceremony grounds, on-site food and bar services, cottages, lodge accommodation and an optional Nordic spa experience. Full-service and intimate, but comparatively expensive.",
 ceremony:"Waterfront ceremony arbour with indoor weather backup included in the 2027 guide.",
 reception:"On-site catered reception, tables, chairs, linens, place settings, setup and teardown listed as facility inclusions.",
 included:["Ceremony arbour and indoor ceremony rain backup","Tables, chairs, linens, place settings and setup/teardown","Catering staff and bartenders","One-night honeymoon cottage and anniversary suite stays","Menu tasting for two","Firewood and SOCAN fees"],
 extra:["2027 facility and food/drink fees not published","Additional mandatory guest-accommodation bookings may apply","Spa access and spa buyouts extra","Tax and gratuity"],
 risks:["$24,000 minimum is historical 2025 pricing only","2027 guide ties exclusivity to reserving all 21 units","Seated capacity around 100 not confirmed"],
 questions:["Please provide the complete September 2027 Saturday fee schedule, including F&B minimums.","Exactly how many of the 21 units must be booked, for how many nights, and who guarantees unsold rooms?","Can 100 people be seated indoors for dinner and dancing, and what tent alternatives exist?","What is the maximum end time for DJ music and the reception?","How do spa, bar gratuities and taxes affect total cost?"],
 imageCredit:"Oceanstone Resort official 2026/2027 wedding gallery."
}
];
